<?php
/**
 * @var $block \OrviSoft\Enhancedecommerce\Block\Tracking\Common
 */
$helper = $this->helper('OrviSoft\Enhancedecommerce\Helper\Track');
?>
<?php if($helper->isActive()): ?>
<!-- Enhanced eCommerce Tracking Header -->
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

ga('create', '<?php echo $helper->getAnalyticsId(); ?>');
ga('require', 'ec');

ga('set', 'currencyCode', 'GBP'); // Set currency to GBP.
ga('send', 'pageview');
</script>
<!-- Enhanced eCommerce Tracking Header -->
<?php endif; ?>